steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: us01pocServiceKeyCred
    integrationFlowId: flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: us01pocServiceKeyCred
    integrationFlowId: flow4
