steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: roverpocServiceKeyCred
    integrationFlowId: flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: roverpocServiceKeyCred
    integrationFlowId: flow4